### ISSUE TITLE
Использование шаблонов в systemd unit

### ISSUE THREAD

**Issue by shaba** [alt-cloud/podsec#25]
Вот такие конструкции выглядят не дистрибутивным решением.
WorkingDirectory=/var/lib/u7s-admin/usernetes
EnvironmentFile=/var/lib/u7s-admin/.config/usernetes/env

Надо использовать шаблоны. Смотри man systemd.unit.
"%u" - User name
"%h" - User home directory
"%t" - Runtime directory root /run, или "$XDG_RUNTIME_DIR" для --user
"%S" - State directory root /var/lib, или "$XDG_CONFIG_HOME" для --user
"%E" - Configuration directory root /etc, или "$XDG_CONFIG_HOME" для --user

**Comment by kafnevod** [comment]
Не нашел шаблонов для
/usr/libexec/
Оставил как есть
