### ISSUE TITLE
Убрать создание unit файлов из скриптов

### ISSUE THREAD

**Issue by shaba** [alt-cloud/podsec#26]
в podsec-u7s-functions создается много unit файлов для systemd.
Будет лучше, если они будут присутствовать в исходниках и упаковываться в пакет(и принадлежать пакету), а не создаваться по месту на сервере.

**Comment by kafnevod** [comment]
Это остатки функционала usernetes
createU7Environments()
checkSystemEnv()
в настоящее время не вызываются и удалены из репозитория
